export { default as Onboarding } from './Onboarding'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Dashboard } from './Dashboard'
export { default as CategoryDetail } from './CategoryDetail'
export { default as ProductDetail } from './ProductDetail'
