export { default as FONT_FAMILY } from './fonts'
export { default as COLORS } from './colors'
export { default as PAYMENT_METHODS } from './paymentMethods'
export { default as TRACKER_STATUS } from './trackerStatus'
export { default as SLIDER_DATA } from './dashboard'
export { default as ONBOARDING_VIEW_DATA } from './screens/onboarding'
